# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_count', models.IntegerField(default=0)),
                ('blue_count', models.IntegerField(default=0)),
            ],
        ),
    ]
